# Stage 1: Build the React app
FROM node:16.20-alpine3.17 AS build

WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the React app's source code to the container
COPY . .

# Build the React app for production
RUN npm run build


# Stage 2: Serve the React app using NGINX
FROM nginx:alpine

# Copy the built React app from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom NGINX configuration (if needed)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 (default HTTP port)
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]





