# Use an official Node.js runtime as the base image
FROM node:16.20-alpine3.17

# Set the working directory inside the container
WORKDIR /richardapp

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose the port that the Node.js app will listen on
EXPOSE 3000

# Start the Node.js application
CMD ["node", "server.js"]






