name: Build and Deploy Docker Image For FrontEnd

on:
  push:
    branches:
      - feature-proproject

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build Docker image
        run: docker build -t murali601135/my-proprojectfrontend-image -f ./frontend/DockerFile .

      # Log in to Docker Hub
      - name: mohan-richee-frontend
        uses: docker/login-action@v1
        with:
          username: murali601135
          password: Mohan@601135

      # Push the image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push murali601135/my-proprojectfrontend-image